-- ===========================================================================
-- 0021: a member may not promote themselves.
--
-- THE HOLE THIS CLOSES. `role` sat in the MEMBERS writable allowlist
-- (functions/api/_shared/contract.ts) beside name, avatar and color, and RLS on
-- public.members is family-tenancy only - the policy generated by the loop in
-- 0002 reads `using (family_id = auth_family_id()) with check (same)` and no
-- policy anywhere mentions role. So a member issuing batchUpdate on their own
-- row with role 'admin' was promoted, with nothing to stop them. Demonstrated
-- against this suite before the fix: the update simply succeeded.
--
-- The asymmetry is what made it a bug rather than a decision: the invite path
-- has always been admin-gated (0007 raises 'admin role required' on both create
-- and revoke), and EVERY legitimate role assignment is already server-side -
-- the founding admin from the sign-up trigger (0001, revised through 0003, 0004
-- and 0010), an invited member's role from the invite row. The client writes
-- role in exactly one place, hardcoded 'member'.
--
-- WHY A TRIGGER AND NOT A POLICY. RLS `with check` sees only the NEW row, and
-- the question here is old-versus-new: "did role change, and may this caller
-- change it". A policy cannot express that. The table already carries per-table
-- triggers, so this is the established shape rather than a new mechanism.
--
-- BEFORE UPDATE ONLY, deliberately. Both legitimate assignments are INSERTs, so
-- an "insert or update" trigger would break sign-up and join_family - and every
-- symptom would surface somewhere else entirely. The suite asserts both insert
-- paths still work, so that choice cannot be quietly widened later.
-- ===========================================================================

create or replace function public.enforce_member_role_change()
  returns trigger
  language plpgsql
  security definer
  set search_path = public, auth
as $$
declare
  caller_role text;
begin
  -- Not a role change: every ordinary member edit (name, avatar, color) lands
  -- here and must pass untouched. The client sends `role` on every member
  -- update, so this branch is the common case rather than an edge.
  if new.role is not distinct from old.role then
    return new;
  end if;

  -- No authenticated caller means a migration or a service-role write, which is
  -- trusted by definition - a data backfill that touches role must not be
  -- blocked by a guard aimed at the client seam. `authenticated` always carries
  -- a uid, so this cannot be reached from the API.
  if auth.uid() is null then
    return new;
  end if;

  -- The caller's OWN membership of the family the row belongs to. Keyed on
  -- new.family_id rather than auth_family_id() so that a row being moved
  -- between families cannot borrow the caller's admin rights in the family they
  -- came from; family_id is not writable and RLS pins it, so this is a belt on
  -- top of a brace and costs nothing.
  select role into caller_role
    from public.members
   where user_id = auth.uid()
     and family_id = new.family_id
   limit 1;

  if caller_role is distinct from 'admin' then
    raise exception 'admin role required to change a member role';
  end if;

  return new;
end;
$$;

drop trigger if exists members_role_change_guard on public.members;
create trigger members_role_change_guard
  before update on public.members
  for each row
  execute function public.enforce_member_role_change();
